GET https://{{PURVIEW_NAME}}.purview.azure.com/catalog/api/atlas/v2/entity/guid/0943290e-52f6-45d7-8821-54f6f6f60000
Authorization: Bearer {{PURVIEW_TOKEN}}

###
# Get entity by attribute

GET https://{{PURVIEW_NAME}}.purview.azure.com/catalog/api/atlas/v2/entity/uniqueAttribute/type/azure_sql_table?attr:qualifiedName=mssql://pvlab-8ca4a6-sqlsvr.database.windows.net/pvlab-8ca4a6-sqldb/SalesLT/Address
Authorization: Bearer {{PURVIEW_TOKEN}}